name: cuML wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  cuml-wheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@feat/wheel-ci-actions-2
    with:
      package-name: cuml
      package-dir: python
      python-package-versioneer-override: "22.10.00a"
      python-package-build-tag: "3"
      python-version: "3.8 3.9"

      manylinux-container-amd64: "rapidsai/manylinux2014"
      manylinux-container-arm64: "rapidsai/manylinux_2_31"

      auditwheel-repair-command-amd64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_17_x86_64 {wheel}"
      auditwheel-repair-command-arm64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_31_aarch64 {wheel}"

      cibw-before-all-amd64: "yum install -y blas-devel lapack-devel"
      cibw-before-all-arm64: "apt-get install -y libblas-dev liblapack-dev"
      cibw-environment: "PIP_INDEX_URL=https://pypi.k8s.rapids.ai/simple"

      skbuild-configure-options: "--log-level=DEBUG -DCUML_RAFT_REPOSITORY=https://github.com/sevagh/raft.git -DCUML_RAFT_BRANCH=feat/cibuildwheel -DCUML_CUMLPRIMS_MG_BRANCH=feat/cibuildwheel -DCPM_DOWNLOAD_ALL=ON -DCUML_BUILD_WHEELS=ON -DDETECT_CONDA_ENV=OFF -DDISABLE_FORCE_CLONE_RAFT=ON -DCMAKE_CUDA_ARCHITECTURES=ALL"

      test-container-amd64: "rapidsai/manylinux_2_27"
      test-container-arm64: "rapidsai/manylinux_2_31"
      test-before-amd64: "pip install rmm-cu11 cudf-cu11 pylibraft-cu11 dask-cudf-cu11 raft-dask-cu11 ucx-py-cu11 --index-url https://pypi.k8s.rapids.ai/simple && pip install git+https://github.com/scikit-learn-contrib/hdbscan.git@master && pip install git+https://github.com/dask/dask-glm@main"
      test-before-arm64: "pip install rmm-cu11 cudf-cu11 pylibraft-cu11 dask-cudf-cu11 raft-dask-cu11 ucx-py-cu11 --index-url https://pypi.k8s.rapids.ai/simple && pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64 && pip install git+https://github.com/scikit-learn-contrib/hdbscan.git@master && pip install git+https://github.com/dask/dask-glm@main"
      test-extras:  "test"
      test-requires: "dask-cuda"
      test-unittest: "pytest -v ./python/cuml/tests"
    secrets: inherit
